[package]
name = "video-analysis-posture"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Pose and skeleton helpers for video-analysis."
readme = "README.md"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde_json.workspace = true
runtime-contracts.workspace = true
math-geometry-2d.workspace = true
serde.workspace = true
three-d-processing-core.workspace = true
video-analysis-core.workspace = true

[dev-dependencies]
num-rational.workspace = true
