[package]
name = "video-analysis-split"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
video-analysis-core.workspace = true

[features]
default = []
external-tests = ["video-analysis-ffmpeg/test-utils"]

[dev-dependencies]
num-rational.workspace = true
tempfile.workspace = true
video-analysis-ffmpeg.workspace = true
video-analysis-test-support.workspace = true
