import type { YoutubeVideoReport } from "@video-analysis/ui";

export const sampleReport: YoutubeVideoReport = {
  use_case: "youtube-video",
  source: {
    url: "https://www.youtube.com/watch?v=sample",
    local_video: "use-case-output/youtube-video/sample-video.mp4",
  },
  assets: {
    work_dir: "use-case-output/youtube-video",
    report_path: "use-case-output/youtube-video/analysis.json",
    audio_wav: "use-case-output/youtube-video/audio.wav",
  },
  capabilities: {
    completed: ["download", "scene-detection", "audio", "transcript", "data-buckets"],
    skipped: ["object-model", "ocr-model"],
  },
  video: {
    width: 1920,
    height: 1080,
    frame_rate: "30000/1001",
    duration_seconds: 94.62,
    frames_processed: 2836,
    scenes: [
      {
        index: 1,
        start_frame: 0,
        end_frame: 423,
        start_seconds: 0,
        end_seconds: 14.11,
        observations: [],
      },
      {
        index: 2,
        start_frame: 423,
        end_frame: 917,
        start_seconds: 14.11,
        end_seconds: 30.6,
        observations: [],
      },
      {
        index: 3,
        start_frame: 917,
        end_frame: 1512,
        start_seconds: 30.6,
        end_seconds: 50.45,
        observations: [],
      },
      {
        index: 4,
        start_frame: 1512,
        end_frame: 2246,
        start_seconds: 50.45,
        end_seconds: 74.94,
        observations: [],
      },
      {
        index: 5,
        start_frame: 2246,
        end_frame: 2836,
        start_seconds: 74.94,
        end_seconds: 94.62,
        observations: [],
      },
    ],
    observations: [
      {
        timestamp_seconds: 12.2,
        frame_index: 366,
        scene_index: 1,
        analyzer: "object-command",
        kind: "Object",
        label: "person",
        score: 0.92,
        region: { x: 712, y: 210, width: 286, height: 612 },
        attributes: { model: "detr-resnet-50" },
      },
      {
        timestamp_seconds: 31.8,
        frame_index: 953,
        scene_index: 3,
        analyzer: "ocr-command",
        kind: "Text",
        text: "Quarterly operating review",
        score: 0.88,
        region: { x: 182, y: 118, width: 760, height: 94 },
        attributes: { language: "en" },
      },
      {
        timestamp_seconds: 56.4,
        frame_index: 1690,
        scene_index: 4,
        analyzer: "scene-classifier",
        kind: "Scene",
        label: "presentation",
        score: 0.81,
        attributes: {},
      },
    ],
  },
  transcription: {
    status: "completed",
    text: "Welcome back. This segment compares the latest visual detections, transcript events, and bucket summaries.",
    message: null,
    segments: [
      {
        index: 0,
        start_seconds: 4.1,
        end_seconds: 9.8,
        text: "Welcome back to the weekly analysis review.",
      },
      {
        index: 1,
        start_seconds: 22.4,
        end_seconds: 27.9,
        text: "The scene changes when the speaker moves from setup to examples.",
      },
      {
        index: 2,
        start_seconds: 61.2,
        end_seconds: 68.7,
        text: "The model outputs are aggregated into stream buckets for the dashboard.",
      },
    ],
  },
  audio: {
    status: "completed",
    frames_processed: 4081,
    message: null,
    events: [
      {
        timestamp_seconds: 5.4,
        analyzer: "audio-energy",
        label: "speech",
        score: 0.76,
      },
      {
        timestamp_seconds: 44.9,
        analyzer: "audio-energy",
        label: "silence",
        score: 0.33,
      },
      {
        timestamp_seconds: 73.8,
        analyzer: "audio-energy",
        label: "speech",
        score: 0.84,
      },
    ],
  },
  text: {
    status: "completed",
    segments_processed: 3,
    message: null,
    events: [
      {
        timestamp_seconds: 22.4,
        analyzer: "transcript-heuristics",
        label: "scene-transition",
        score: 0.71,
      },
      {
        timestamp_seconds: 61.2,
        analyzer: "transcript-heuristics",
        label: "model-output",
        score: 0.69,
      },
    ],
  },
  data_buckets: [
    {
      bucket_index: 0,
      records: 880,
      estimated_bytes: 1854000,
      streams: [
        {
          stream_id: "video:frames",
          records: 423,
          estimated_bytes: 1402000,
          payload_counts: { Video: 423 },
          video_frames: 423,
          audio_frames: 0,
          text_segments: 0,
        },
        {
          stream_id: "audio:energy",
          records: 455,
          estimated_bytes: 450000,
          payload_counts: { Audio: 455 },
          video_frames: 0,
          audio_frames: 455,
          text_segments: 0,
        },
        {
          stream_id: "text:transcript",
          records: 2,
          estimated_bytes: 2000,
          payload_counts: { Text: 2 },
          video_frames: 0,
          audio_frames: 0,
          text_segments: 2,
        },
      ],
    },
    {
      bucket_index: 1,
      records: 1134,
      estimated_bytes: 2569000,
      streams: [
        {
          stream_id: "video:frames",
          records: 595,
          estimated_bytes: 1989000,
          payload_counts: { Video: 595 },
          video_frames: 595,
          audio_frames: 0,
          text_segments: 0,
        },
        {
          stream_id: "audio:energy",
          records: 538,
          estimated_bytes: 578000,
          payload_counts: { Audio: 538 },
          video_frames: 0,
          audio_frames: 538,
          text_segments: 0,
        },
        {
          stream_id: "text:transcript",
          records: 1,
          estimated_bytes: 2000,
          payload_counts: { Text: 1 },
          video_frames: 0,
          audio_frames: 0,
          text_segments: 1,
        },
      ],
    },
    {
      bucket_index: 2,
      records: 822,
      estimated_bytes: 1603000,
      streams: [
        {
          stream_id: "video:frames",
          records: 590,
          estimated_bytes: 1472000,
          payload_counts: { Video: 590 },
          video_frames: 590,
          audio_frames: 0,
          text_segments: 0,
        },
        {
          stream_id: "audio:energy",
          records: 232,
          estimated_bytes: 131000,
          payload_counts: { Audio: 232 },
          video_frames: 0,
          audio_frames: 232,
          text_segments: 0,
        },
      ],
    },
  ],
};
