#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORPORA_DIR="${TEST_CORPORA_DIR:-"$ROOT_DIR/.test-corpora"}"
UNICODE_VERSION="${UNICODE_VERSION:-17.0.0}"
REFRESH="${REFRESH_TEST_CORPORA:-0}"

mkdir -p "$CORPORA_DIR"

usage() {
  cat <<'USAGE'
Usage: scripts/download_test_corpora.sh [target...]

Targets:
  default        Download the portable corpus set: unicode, nltk, ud, video-metadata, manifests.
  unicode        Unicode UAX #29 boundary conformance test files.
  nltk           Common NLTK text corpora zips: Brown, Reuters, Gutenberg, movie_reviews, stopwords.
  ud             Selected Universal Dependencies treebanks.
  video-metadata Public annotation/code repos for ClipShots, AutoShot, and GEBD.
  manifests      Write notes for large or access-gated corpora.
  nsynth-test    Download NSynth test TFRecord. Requires DOWNLOAD_LARGE_CORPORA=1.
  all            default plus nsynth-test.

Environment:
  TEST_CORPORA_DIR=/path     Destination directory. Defaults to .test-corpora.
  UNICODE_VERSION=17.0.0     Unicode data version for UAX #29 files.
  REFRESH_TEST_CORPORA=1     Re-download existing files.
  DOWNLOAD_LARGE_CORPORA=1   Allow large opt-in downloads.
  UD_TREEBANKS="repo ..."    Override selected UD repository names.
USAGE
}

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command '$1' is unavailable" >&2
    exit 1
  fi
}

download_file() {
  local url="$1"
  local dest="$2"
  local label="${3:-$dest}"
  local tmp="$dest.tmp"

  mkdir -p "$(dirname "$dest")"
  if [[ "$REFRESH" != "1" && -s "$dest" ]]; then
    echo "exists: $label"
    return
  fi

  echo "download: $label"
  curl -fL --retry 3 --connect-timeout 30 --output "$tmp" "$url"
  mv "$tmp" "$dest"
  printf '%s\n' "$url" > "$dest.source-url"
}

extract_zip() {
  local zip_path="$1"
  local dest_dir="$2"
  local marker="$dest_dir/.extracted-$(basename "$zip_path")"

  mkdir -p "$dest_dir"
  if [[ "$REFRESH" != "1" && -f "$marker" ]]; then
    echo "exists: extracted $(basename "$zip_path")"
    return
  fi

  need unzip
  echo "extract: $(basename "$zip_path")"
  unzip -q -o "$zip_path" -d "$dest_dir"
  date -u +"%Y-%m-%dT%H:%M:%SZ" > "$marker"
}

clone_or_update() {
  local url="$1"
  local dest="$2"
  local label="${3:-$dest}"

  if [[ -d "$dest/.git" ]]; then
    echo "update: $label"
    if ! git -C "$dest" pull --ff-only --quiet; then
      echo "warning: could not fast-forward $label; leaving existing checkout unchanged" >&2
    fi
    return
  fi

  if [[ -e "$dest" ]]; then
    echo "exists: $label (not a git checkout)"
    return
  fi

  echo "clone: $label"
  git clone --depth 1 --quiet "$url" "$dest"
}

write_manifest() {
  cat > "$CORPORA_DIR/README.md" <<'EOF'
# Test Corpora

This directory is generated by `scripts/download_test_corpora.sh` and is ignored
by git. Do not commit downloaded datasets, extracted corpora, model files, or
archives from this directory.

The default target fetches small-to-moderate fixtures that are practical for
local parser, tokenizer, corpus, and detector development:

- `unicode/`: Unicode UAX #29 grapheme, word, sentence, and line break tests.
- `nltk/`: Brown, Reuters, Gutenberg, movie_reviews, and stopwords corpora.
- `universal-dependencies/`: selected UD treebank git checkouts.
- `video-metadata/`: annotation/code repositories for ClipShots, AutoShot, and
  GEBD. These are not the full video payloads.

Large or access-controlled datasets need explicit handling:

- TRECVID Shot Boundary Detection: requires NIST data request forms.
- MUSDB18 / MUSDB18-HQ: hosted on Zenodo and requires access approval.
- HEAR / DCASE: use the task-specific official download instructions.
- ClipShots / AutoShot full videos: hosted outside the metadata repositories and
  can be very large.
- NSynth: `scripts/download_test_corpora.sh nsynth-test` downloads only the test
  TFRecord and requires `DOWNLOAD_LARGE_CORPORA=1`.
EOF

  cat > "$CORPORA_DIR/large-corpora.tsv" <<'EOF'
name	status	url	notes
TRECVID_SBD	manual_request	https://trecvid.nist.gov/past.data.table.html	NIST forms are required for many historical SBD datasets.
MUSDB18	manual_request	https://sigsep.github.io/datasets/musdb.html	Zenodo-hosted, access-controlled, approximately 4.4 GB compressed STEMS.
MUSDB18_HQ	manual_request	https://sigsep.github.io/datasets/musdb.html	Zenodo-hosted, access-controlled, approximately 22.7 GB WAV.
HEAR	official_tooling	https://hearbenchmark.com/hear-tasks.html	Use HEAR's Zenodo/cloud mirrors and task-specific instructions.
DCASE	official_tooling	https://dcase.community/	Use challenge-specific dataset pages and licenses.
ClipShots_full_video	external_large	https://github.com/Tangshitao/ClipShots	Metadata repo is downloaded by default; videos are hosted separately.
AutoShot_full_video	external_large	https://github.com/wentaozhu/AutoShot	Metadata repo is downloaded by default; videos are hosted separately.
EOF
}

download_unicode() {
  need curl
  local base="https://www.unicode.org/Public/$UNICODE_VERSION/ucd/auxiliary"
  local dest="$CORPORA_DIR/unicode/$UNICODE_VERSION"

  download_file "$base/GraphemeBreakTest.txt" "$dest/GraphemeBreakTest.txt" "Unicode GraphemeBreakTest $UNICODE_VERSION"
  download_file "$base/WordBreakTest.txt" "$dest/WordBreakTest.txt" "Unicode WordBreakTest $UNICODE_VERSION"
  download_file "$base/SentenceBreakTest.txt" "$dest/SentenceBreakTest.txt" "Unicode SentenceBreakTest $UNICODE_VERSION"
  download_file "$base/LineBreakTest.txt" "$dest/LineBreakTest.txt" "Unicode LineBreakTest $UNICODE_VERSION"
}

download_nltk() {
  need curl
  local base="https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora"
  local dest="$CORPORA_DIR/nltk"
  local corpus
  local corpora=(brown reuters gutenberg movie_reviews stopwords)

  mkdir -p "$dest/archives" "$dest/extracted"
  for corpus in "${corpora[@]}"; do
    download_file "$base/$corpus.zip" "$dest/archives/$corpus.zip" "NLTK $corpus.zip"
    extract_zip "$dest/archives/$corpus.zip" "$dest/extracted"
  done
}

download_ud() {
  need git
  local dest="$CORPORA_DIR/universal-dependencies"
  local treebanks_string="${UD_TREEBANKS:-UD_English-EWT UD_German-GSD UD_Chinese-GSD UD_Japanese-GSD UD_Arabic-PADT}"
  local treebank

  mkdir -p "$dest"
  for treebank in $treebanks_string; do
    clone_or_update \
      "https://github.com/UniversalDependencies/$treebank.git" \
      "$dest/$treebank" \
      "UniversalDependencies/$treebank"
  done
}

download_video_metadata() {
  need git
  local dest="$CORPORA_DIR/video-metadata"

  mkdir -p "$dest"
  clone_or_update "https://github.com/Tangshitao/ClipShots.git" "$dest/ClipShots" "ClipShots metadata"
  clone_or_update "https://github.com/wentaozhu/AutoShot.git" "$dest/AutoShot" "AutoShot metadata"
  clone_or_update "https://github.com/StanLei52/GEBD.git" "$dest/GEBD" "GEBD metadata"
}

download_nsynth_test() {
  if [[ "${DOWNLOAD_LARGE_CORPORA:-0}" != "1" ]]; then
    echo "error: nsynth-test is large; set DOWNLOAD_LARGE_CORPORA=1 to download it" >&2
    exit 1
  fi

  need curl
  download_file \
    "http://download.magenta.tensorflow.org/datasets/nsynth/nsynth-test.tfrecord" \
    "$CORPORA_DIR/nsynth/nsynth-test.tfrecord" \
    "NSynth test TFRecord"
}

run_target() {
  case "$1" in
    default)
      download_unicode
      download_nltk
      download_ud
      download_video_metadata
      write_manifest
      ;;
    unicode) download_unicode ;;
    nltk) download_nltk ;;
    ud) download_ud ;;
    video-metadata) download_video_metadata ;;
    manifests) write_manifest ;;
    nsynth-test) download_nsynth_test ;;
    all)
      run_target default
      download_nsynth_test
      ;;
    -h|--help|help) usage ;;
    *)
      echo "error: unknown target '$1'" >&2
      usage >&2
      exit 1
      ;;
  esac
}

if [[ "$#" -eq 0 ]]; then
  set -- default
fi

for target in "$@"; do
  run_target "$target"
done

echo "test corpora are under $CORPORA_DIR"
