#!/usr/bin/env bash
# shellcheck shell=bash

# Model bundle specs (tracked, small text file):
# - model_preset <preset> [revision] [name_override]
# - model_custom <name> <repo_id> <task> <revision> <file>...
#
# Example:
# model_preset "xenova-distilbert-sst2-onnx" "main"
# model_custom "tiny-random-bert" "hf-internal-testing/tiny-random-bert" "text-embedding" "main" \
#   "config.json" "model.safetensors"
#
# After adding or changing specs, run:
#   bash scripts/sync_model_bundles.sh --write-lock
#
# For day-to-day idempotent verification + auto-repair, run:
#   bash scripts/sync_model_bundles.sh
#
# For CI verification only, run:
#   bash scripts/sync_model_bundles.sh --check

# BEGIN AUTO-CHECKSUMS
# Generated by scripts/sync_model_bundles.sh --write-lock
# END AUTO-CHECKSUMS
