#!/usr/bin/env bash
# shellcheck shell=bash

# Model bundle specs (tracked, small text file):
# - model_preset <preset> [revision] [name_override]
# - model_custom <name> <repo_id> <task> <revision> <file>...
#
# Example:
# model_preset "xenova-distilbert-sst2-onnx" "main"
# model_custom "tiny-random-bert" "hf-internal-testing/tiny-random-bert" "text-embedding" "main" \
#   "config.json" "model.safetensors"
#
# Text classification external smokes use:
# model_preset "distilbert-sst2" "main"
# model_preset "xenova-bart-large-mnli-onnx" "main"
#
# After adding or changing specs, run:
#   bash scripts/sync_model_bundles.sh --write-lock
#
# For day-to-day idempotent verification + auto-repair, run:
#   bash scripts/sync_model_bundles.sh
#
# For CI verification only, run:
#   bash scripts/sync_model_bundles.sh --check

model_preset "wav2vec2-base-960h" "main"
model_preset "trocr-base-printed-onnx" "main"

model_custom "wespeaker-voxceleb-resnet34-LM" \
  "hbredin/wespeaker-voxceleb-resnet34-LM" \
  "audio-embedding" \
  "main" \
  "speaker-embedding.onnx"


# BEGIN AUTO-CHECKSUMS
# Generated by scripts/sync_model_bundles.sh --write-lock on 2026-06-13T20:51:41Z
model_sha256 trocr-base-printed-onnx main config.json 2d977c109466628b177fb00466d850aaa254ec934deb3d75ddd09ccd3e25c78d
model_sha256 trocr-base-printed-onnx main generation_config.json cce308da91e0d656e07404c70d4b9c9f5839d426f679eff6fda6dcc0e727e3b6
model_sha256 trocr-base-printed-onnx main merges.txt 1ce1664773c50f3e0cc8842619a93edc4624525b728b188a9e0be33b7726adc5
model_sha256 trocr-base-printed-onnx main onnx/decoder_model_quantized.onnx 60c8ca1b1bd99a6f469c8db1c979db700b50b18bc97ed790429e33f8964bfba6
model_sha256 trocr-base-printed-onnx main onnx/encoder_model_quantized.onnx b9df248ebb648f3f0cb606e2e650d74942a324cd2dc94245206a88291ee3d52a
model_sha256 trocr-base-printed-onnx main preprocessor_config.json 0860b87c599518cc75f8d9bdb2eaa99897406b76bbe273055a389c9f81c9c387
model_sha256 trocr-base-printed-onnx main tokenizer.json 2f1a555a1ee93656b4e6f67aa75d492a843c225e5ef754bae24c36bd85851cd7
model_sha256 trocr-base-printed-onnx main tokenizer_config.json 3a40c2212f1f261462a4604781d1c8984090a7d9467ff6f3ad6d945d4d76ca64
model_sha256 trocr-base-printed-onnx main vocab.json ed19656ea1707df69134c4af35c8ceda2cc9860bf2c3495026153a133670ab5e
model_sha256 wav2vec2-base-960h main config.json d3ec255c063d9f95057b553b19c20135b259875834a4fe9deb218a6be25b4cf3
model_sha256 wav2vec2-base-960h main model.safetensors 8aa76ab2243c81747a1f832954586bc566090c83a0ac167df6f31f0fa917d74a
model_sha256 wav2vec2-base-960h main preprocessor_config.json b225d617c025463b9e157e06afea8b90dc7078fc70b013c533328423e0486b4a
model_sha256 wav2vec2-base-960h main vocab.json 19727f8944fe6459fc3f240ae2c198395b740f6a029bd23e06656266b83bcf64
model_sha256 wespeaker-voxceleb-resnet34-LM main speaker-embedding.onnx 7bb2f06e9df17cdf1ef14ee8a15ab08ed28e8d0ef5054ee135741560df2ec068
# END AUTO-CHECKSUMS
