#!/usr/bin/env bash
# shellcheck shell=bash

# Model bundle specs (tracked, small text file):
# - model_preset <preset> [revision] [name_override]
# - model_custom <name> <repo_id> <task> <revision> <file>...
#
# Example:
# model_preset "xenova-distilbert-sst2-onnx" "main"
# model_custom "tiny-random-bert" "hf-internal-testing/tiny-random-bert" "text-embedding" "main" \
#   "config.json" "model.safetensors"
#
# Text classification external smokes use:
# model_preset "distilbert-sst2" "main"
# model_preset "xenova-bart-large-mnli-onnx" "main"
#
# After adding or changing specs, run:
#   bash scripts/sync_model_bundles.sh --write-lock
#
# For day-to-day idempotent verification + auto-repair, run:
#   bash scripts/sync_model_bundles.sh
#
# For CI verification only, run:
#   bash scripts/sync_model_bundles.sh --check

model_preset "wav2vec2-base-960h" "main"

model_custom "wespeaker-voxceleb-resnet34-LM" \
  "hbredin/wespeaker-voxceleb-resnet34-LM" \
  "audio-embedding" \
  "main" \
  "speaker-embedding.onnx"


# BEGIN AUTO-CHECKSUMS
# Generated by scripts/sync_model_bundles.sh --write-lock on 2026-06-10T16:24:31Z
model_sha256 wav2vec2-base-960h main config.json d3ec255c063d9f95057b553b19c20135b259875834a4fe9deb218a6be25b4cf3
model_sha256 wav2vec2-base-960h main model.safetensors 8aa76ab2243c81747a1f832954586bc566090c83a0ac167df6f31f0fa917d74a
model_sha256 wav2vec2-base-960h main preprocessor_config.json b225d617c025463b9e157e06afea8b90dc7078fc70b013c533328423e0486b4a
model_sha256 wav2vec2-base-960h main vocab.json 19727f8944fe6459fc3f240ae2c198395b740f6a029bd23e06656266b83bcf64
model_sha256 wespeaker-voxceleb-resnet34-LM main speaker-embedding.onnx 7bb2f06e9df17cdf1ef14ee8a15ab08ed28e8d0ef5054ee135741560df2ec068
# END AUTO-CHECKSUMS
