[package]
name = "video-analysis-use-cases"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "video-analysis-use-cases"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
text-analysis-features.workspace = true
text-analysis-transcription.workspace = true
video-analysis-core.workspace = true
video-analysis-data.workspace = true
video-analysis-detectors.workspace = true
video-analysis-ffmpeg.workspace = true
video-analysis-ingest.workspace = true
video-analysis-models.workspace = true
video-analysis-radiance-pipeline.workspace = true

[dev-dependencies]
tempfile.workspace = true
video-analysis-ffmpeg = { workspace = true, features = ["test-utils"] }
video-analysis-test-support.workspace = true
